### PR TITLE
Changed all keyword mentions to KEYWORDS list

### PR DESCRIPTION
**Pull request by quantum9Innovation**
This allows for an easy change to the KEYWORDS list that will not involve changing every single mention. Additionally, this speeds up the process of finding errors in the code since all keywords come from the KEYWORDS list.

**Known Bugs**:
 - Some error strings may have been changed to `KEYWORDS[i]` where i is the index of the keyword instead of properly displaying the keyword

### CODE REVIEW

**Comment by quantum9Innovation** [comment]
This close was unnecessary, **all checks are passing!** :heavy_check_mark:

**Comment by Quantalabs** [comment]
Keywords do not need to be improved.

**Comment by quantum9Innovation** [comment]
:question: :question: :question:

**Comment by quantum9Innovation** [comment]
> question question question

**Restoration is an order!**

**Pull request closed without merging**
